x-custom-metadata:
  version: 1.0.0
  last-updated: 2025-10-16

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      sonarqube-dev:
        ipv4_address: 152.18.0.2  #Docker reserves 1 to gateway
    volumes:
      - ./sonar/conf/sonar.properties:/opt/sonarqube/conf/sonar.properties:ro
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - '9000:9000'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_temp:

networks:
    sonarqube-dev:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 152.18.0.0/24

